# Generated by Django 3.2.14 on 2022-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default='2022-09-09'),
            preserve_default=False,
        ),
    ]
