# Generated by Django 3.2.14 on 2022-08-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('grpup_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
                ('group_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_groups',
            field=models.JSONField(default='{"goups":[are here]}'),
            preserve_default=False,
        ),
    ]
