# Generated by Django 3.2.14 on 2022-08-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_group_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_groups',
        ),
    ]
