# Generated by Django 3.2.14 on 2022-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customuser_user_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='grpup_id',
            new_name='group_id',
        ),
    ]
