# Generated by Django 3.2.14 on 2022-08-26 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_grpup_id_group_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_icon',
            new_name='group_back',
        ),
        migrations.AddField(
            model_name='group',
            name='group_created',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 4, 45, 13, 822718, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='group',
            name='group_creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_admin',
            field=models.JSONField(),
        ),
    ]
