# Generated by Django 3.2.14 on 2022-08-26 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220825_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 7, 22, 21, 799000, tzinfo=utc)),
        ),
    ]
