# Generated by Django 3.2.14 on 2022-08-26 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220826_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 7, 27, 12, 9550, tzinfo=utc)),
        ),
    ]
