# Generated by Django 3.2.14 on 2022-08-26 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_group_group_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feelings',
            fields=[
                ('emoji_id', models.AutoField(primary_key=True, serialize=False)),
                ('emoji_name', models.CharField(max_length=30)),
                ('emoji_emoji', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 9, 15, 25, 444748, tzinfo=utc)),
        ),
    ]
