# Generated by Django 3.2.14 on 2022-08-27 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_group_group_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelings',
            name='emoji_type',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 6, 30, 53, 670786, tzinfo=utc)),
        ),
    ]
