# Generated by Django 3.2.14 on 2022-08-27 08:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220827_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 8, 37, 48, 189773, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.TextField(max_length=300, null=True)),
                ('post_text', models.TextField(null=True)),
                ('post_tag_user', models.JSONField(null=True)),
                ('post_time_stamp', models.DateTimeField(default=datetime.datetime(2022, 8, 27, 8, 37, 48, 205378, tzinfo=utc))),
                ('post_backgound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.backpost')),
                ('post_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_feelings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.feelings')),
                ('post_gif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.gif')),
            ],
        ),
    ]
