# Generated by Django 3.2.14 on 2022-08-27 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220827_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 8, 54, 44, 987877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_gif',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 8, 54, 44, 987877, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Gif',
        ),
    ]
