# Generated by Django 3.2.14 on 2022-08-29 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220827_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 33, 42, 635299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 33, 42, 635299, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField()),
                ('page_web', models.URLField(max_length=400, null=True)),
                ('page_desc', models.TextField(null=True)),
                ('page_phone', models.CharField(max_length=30, null=True)),
                ('page_email', models.EmailField(max_length=150, null=True)),
                ('page_profile', models.ImageField(null=True, upload_to='page_profile')),
                ('page_cover', models.ImageField(null=True, upload_to='page_cover')),
                ('page_admin', models.JSONField()),
                ('page_time_stamp', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 33, 42, 635299, tzinfo=utc))),
                ('page_like_count', models.IntegerField(max_length=100)),
                ('page_username', models.TextField(null=True, unique=True)),
                ('page_modified', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 33, 42, 635299, tzinfo=utc))),
                ('page_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
