# Generated by Django 3.2.14 on 2022-08-29 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220829_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 41, 22, 605054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 41, 22, 605054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 41, 22, 605054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 9, 41, 22, 605054, tzinfo=utc)),
        ),
    ]
