# Generated by Django 3.2.14 on 2022-08-30 06:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220829_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 6, 9, 30, 604293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 6, 9, 30, 604293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 6, 9, 30, 604293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 6, 9, 30, 604293, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('story_type', models.JSONField()),
                ('story_text', models.TextField(max_length=300)),
                ('story_media', models.FileField(null=True, upload_to='story_media')),
                ('story_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
