# Generated by Django 4.0.6 on 2022-08-31 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220830_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='wesy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 7, 9, 36, 656651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 7, 9, 36, 657266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 7, 9, 36, 657225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 7, 9, 36, 659156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 7, 9, 36, 658081, tzinfo=utc)),
        ),
    ]
