# Generated by Django 4.1 on 2022-09-12 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_delete_ali_alter_group_group_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_media', models.FileField(upload_to='userpostimages')),
                ('post_text', models.TextField()),
                ('post_created', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 40, 28, 866313, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 40, 28, 867004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 40, 28, 868147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 40, 28, 868076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 40, 28, 871579, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 40, 28, 869613, tzinfo=datetime.timezone.utc)),
        ),
    ]
