# Generated by Django 4.1 on 2022-09-13 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_group_group_created_alter_page_page_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 460038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 460535, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 460504, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 462097, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 459177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 459569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 458754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 57, 49, 461170, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_aboutme', models.TextField(max_length=500)),
                ('profile_activities', models.TextField()),
                ('profile_afflicationcourt', models.TextField()),
                ('profile_favoraitbooks', models.TextField()),
                ('profile_favoraitmovies', models.TextField()),
                ('profile_favoraitmusics', models.TextField()),
                ('profile_favoraitquotes', models.TextField()),
                ('profile_favoraittvshows', models.TextField()),
                ('profile_intrests', models.TextField()),
                ('profile_notescourts', models.TextField()),
                ('profile_picture', models.FileField(upload_to='profile_picture')),
                ('profile_politicalviews', models.TextField()),
                ('profile_religion', models.TextField()),
                ('profile_schoolcourt', models.TextField()),
                ('profile_significantid', models.TextField()),
                ('profile_wallcourt', models.TextField()),
                ('profile_addfriendlink', models.TextField()),
                ('profile_notesbyuserlink', models.TextField()),
                ('profile_pictuersbyuserlink', models.TextField()),
                ('profile_pictuersofuserlink', models.TextField()),
                ('profile_postonuserlink', models.TextField()),
                ('profile_profilelink', models.TextField()),
                ('profile_sendmessagelink', models.TextField()),
                ('profile_workplacecourt', models.TextField()),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
