# Generated by Django 4.1 on 2022-09-13 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_group_group_created_alter_page_page_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_addfriendlink',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_notesbyuserlink',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pictuersbyuserlink',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pictuersofuserlink',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_postonuserlink',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_profilelink',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_sendmessagelink',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 304187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 304680, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 304652, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 306260, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 303216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 303602, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 302782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 15, 4, 305326, tzinfo=datetime.timezone.utc)),
        ),
    ]
