# Generated by Django 4.1 on 2022-09-15 08:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_postuser_post_comments_postuser_post_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 213314, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 213810, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 213782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 216479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 211984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 212428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 211564, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 214465, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AddFriend',
            fields=[
                ('addfriend_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('addfreind_reciever', models.CharField(max_length=20)),
                ('addfreind_status', models.CharField(max_length=15)),
                ('addfreind_created', models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 212893, tzinfo=datetime.timezone.utc))),
                ('addfreind_updated', models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 59, 38, 212906, tzinfo=datetime.timezone.utc))),
                ('addfreind_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
