# Generated by Django 4.1 on 2022-09-19 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_group_group_created_alter_page_page_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 23267, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_friendscount',
            field=models.IntegerField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_groupcount',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 23284, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 25078, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 25090, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 25494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 25992, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 25961, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 28712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 24214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 24616, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 23800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 4, 44, 26729, tzinfo=datetime.timezone.utc)),
        ),
    ]
