# Generated by Django 4.1 on 2022-09-19 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_profile_profile_created_profile_profile_friendscount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_admin',
        ),
        migrations.AddField(
            model_name='group',
            name='group_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 759506, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 759048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 759060, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 759495, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 759993, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 759965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 762484, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 758146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 758587, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 757701, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 757144, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 757160, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 41, 57, 760648, tzinfo=datetime.timezone.utc)),
        ),
    ]
