# Generated by Django 4.1 on 2022-09-19 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_groupmember_alter_addfriend_addfreind_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='gmember_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmember',
            name='gmember_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 75603, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 75615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 76013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 76025, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 76421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 76434, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 76936, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 76905, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 79801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 74720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 75132, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 74178, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 73641, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 73659, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 4, 57, 33, 77631, tzinfo=datetime.timezone.utc)),
        ),
    ]
