# Generated by Django 4.1 on 2022-09-23 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_mchatsms_sms_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchatsms',
            name='sms_mchat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.mchat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 293573, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 293587, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 294408, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 294419, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 294824, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 294835, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mchat',
            name='mchat_user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mchat',
            name='mchat_user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mchatsms',
            name='sms_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 296039, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 296826, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 296799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 298635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 292800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 293185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 292303, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 291776, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 291792, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 297476, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Blockuser',
            fields=[
                ('blockuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('blockuser_timestamp', models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 293965, tzinfo=datetime.timezone.utc))),
                ('blockuser_update', models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 55, 30, 293978, tzinfo=datetime.timezone.utc))),
                ('blockuser_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL)),
                ('blockuser_blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
