# Generated by Django 4.1 on 2022-09-23 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_mchatsms_sms_mchat_alter_addfriend_addfreind_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchatsms',
            name='sms_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.mchatsms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 202838, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 202853, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockuser',
            name='blockuser_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 203275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blockuser',
            name='blockuser_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 203288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 203770, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 203782, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 204200, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 204212, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mchatsms',
            name='sms_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mchatsms',
            name='sms_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 205439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 206281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 206253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 208022, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 202043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 202438, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 201518, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 200968, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 200984, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 17, 31, 10, 206939, tzinfo=datetime.timezone.utc)),
        ),
    ]
