# Generated by Django 3.2 on 2022-10-02 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_addfriend_addfreind_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='addfreind_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockuser',
            name='blockuser_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blockuser',
            name='blockuser_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gmember_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mchatsms',
            name='sms_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 123869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 131864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 131864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 131864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 115867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 107881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 107881, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 107881, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 5, 9, 39, 131864, tzinfo=utc)),
        ),
    ]
